/*
 * generated by Xtext 2.37.0
 */
package de.cau.cs.kieler.railsl.ui;

import com.google.inject.Injector;
import de.cau.cs.kieler.railsl.ui.internal.RailslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RailSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RailslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RailslActivator activator = RailslActivator.getInstance();
		return activator != null ? activator.getInjector(RailslActivator.DE_CAU_CS_KIELER_RAILSL_RAILSL) : null;
	}

}
