/**
 * generated by Xtext 2.16.0
 */
package de.cau.cs.kieler.railsl.railSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.Block#getStatements <em>Statements</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.Block#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getBlock()
 * @model
 * @generated
 */
public interface Block extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link de.cau.cs.kieler.railsl.railSL.Statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getBlock_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * The literals are from the enumeration {@link de.cau.cs.kieler.railsl.railSL.BlockEnd}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.BlockEnd
   * @see #setEnd(BlockEnd)
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getBlock_End()
   * @model
   * @generated
   */
  BlockEnd getEnd();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.railsl.railSL.Block#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.BlockEnd
   * @see #getEnd()
   * @generated
   */
  void setEnd(BlockEnd value);

} // Block
