/**
 * generated by Xtext 2.37.0
 */
package de.cau.cs.kieler.railsl.railSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional Line</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.ConditionalLine#getContact <em>Contact</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.ConditionalLine#getSegment <em>Segment</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.ConditionalLine#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getConditionalLine()
 * @model
 * @generated
 */
public interface ConditionalLine extends EObject
{
  /**
   * Returns the value of the '<em><b>Contact</b></em>' attribute.
   * The literals are from the enumeration {@link de.cau.cs.kieler.railsl.railSL.ContactPosition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contact</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.ContactPosition
   * @see #setContact(ContactPosition)
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getConditionalLine_Contact()
   * @model
   * @generated
   */
  ContactPosition getContact();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.railsl.railSL.ConditionalLine#getContact <em>Contact</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contact</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.ContactPosition
   * @see #getContact()
   * @generated
   */
  void setContact(ContactPosition value);

  /**
   * Returns the value of the '<em><b>Segment</b></em>' attribute.
   * The literals are from the enumeration {@link de.cau.cs.kieler.railsl.railSL.RailSegment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segment</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.RailSegment
   * @see #setSegment(RailSegment)
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getConditionalLine_Segment()
   * @model
   * @generated
   */
  RailSegment getSegment();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.railsl.railSL.ConditionalLine#getSegment <em>Segment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Segment</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.RailSegment
   * @see #getSegment()
   * @generated
   */
  void setSegment(RailSegment value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(Block)
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getConditionalLine_Block()
   * @model containment="true"
   * @generated
   */
  Block getBlock();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.railsl.railSL.ConditionalLine#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(Block value);

} // ConditionalLine
