/**
 * generated by Xtext 2.37.0
 */
package de.cau.cs.kieler.railsl.railSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Track Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.TrackStatement#getSegments <em>Segments</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.TrackStatement#getSpeed <em>Speed</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.TrackStatement#isReverse <em>Reverse</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getTrackStatement()
 * @model
 * @generated
 */
public interface TrackStatement extends SetStatement
{
  /**
   * Returns the value of the '<em><b>Segments</b></em>' attribute list.
   * The list contents are of type {@link de.cau.cs.kieler.railsl.railSL.RailSegment}.
   * The literals are from the enumeration {@link de.cau.cs.kieler.railsl.railSL.RailSegment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segments</em>' attribute list.
   * @see de.cau.cs.kieler.railsl.railSL.RailSegment
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getTrackStatement_Segments()
   * @model unique="false"
   * @generated
   */
  EList<RailSegment> getSegments();

  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * The literals are from the enumeration {@link de.cau.cs.kieler.railsl.railSL.TrackSpeed}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.TrackSpeed
   * @see #setSpeed(TrackSpeed)
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getTrackStatement_Speed()
   * @model
   * @generated
   */
  TrackSpeed getSpeed();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.railsl.railSL.TrackStatement#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see de.cau.cs.kieler.railsl.railSL.TrackSpeed
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(TrackSpeed value);

  /**
   * Returns the value of the '<em><b>Reverse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reverse</em>' attribute.
   * @see #setReverse(boolean)
   * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getTrackStatement_Reverse()
   * @model
   * @generated
   */
  boolean isReverse();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.railsl.railSL.TrackStatement#isReverse <em>Reverse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reverse</em>' attribute.
   * @see #isReverse()
   * @generated
   */
  void setReverse(boolean value);

} // TrackStatement
