/*
 * generated by Xtext 2.10.0
 */
package de.cau.cs.kieler.railsl.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RailSLValidator extends de.cau.cs.kieler.railsl.validation.AbstractRailSLValidator {
	
}
