/**
 * generated by Xtext 2.14.0
 */
package de.cau.cs.kieler.railsl.railSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wait Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cau.cs.kieler.railsl.railSL.RailSLPackage#getWaitStatement()
 * @model
 * @generated
 */
public interface WaitStatement extends Statement
{
} // WaitStatement
