/**
 * generated by Xtext 2.16.0
 */
package de.cau.cs.kieler.railsl.railSL.impl;

import de.cau.cs.kieler.railsl.railSL.ContactEvent;
import de.cau.cs.kieler.railsl.railSL.ContactPosition;
import de.cau.cs.kieler.railsl.railSL.ContactWaitStatement;
import de.cau.cs.kieler.railsl.railSL.RailSLPackage;
import de.cau.cs.kieler.railsl.railSL.RailSegment;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Contact Wait Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.impl.ContactWaitStatementImpl#getEvent <em>Event</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.impl.ContactWaitStatementImpl#getContact <em>Contact</em>}</li>
 *   <li>{@link de.cau.cs.kieler.railsl.railSL.impl.ContactWaitStatementImpl#getSegment <em>Segment</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContactWaitStatementImpl extends WaitStatementImpl implements ContactWaitStatement
{
  /**
   * The default value of the '{@link #getEvent() <em>Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvent()
   * @generated
   * @ordered
   */
  protected static final ContactEvent EVENT_EDEFAULT = ContactEvent.REACH;

  /**
   * The cached value of the '{@link #getEvent() <em>Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvent()
   * @generated
   * @ordered
   */
  protected ContactEvent event = EVENT_EDEFAULT;

  /**
   * The default value of the '{@link #getContact() <em>Contact</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContact()
   * @generated
   * @ordered
   */
  protected static final ContactPosition CONTACT_EDEFAULT = ContactPosition.FIRST;

  /**
   * The cached value of the '{@link #getContact() <em>Contact</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContact()
   * @generated
   * @ordered
   */
  protected ContactPosition contact = CONTACT_EDEFAULT;

  /**
   * The default value of the '{@link #getSegment() <em>Segment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSegment()
   * @generated
   * @ordered
   */
  protected static final RailSegment SEGMENT_EDEFAULT = RailSegment.IC_JCT_0;

  /**
   * The cached value of the '{@link #getSegment() <em>Segment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSegment()
   * @generated
   * @ordered
   */
  protected RailSegment segment = SEGMENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContactWaitStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RailSLPackage.Literals.CONTACT_WAIT_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ContactEvent getEvent()
  {
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEvent(ContactEvent newEvent)
  {
    ContactEvent oldEvent = event;
    event = newEvent == null ? EVENT_EDEFAULT : newEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailSLPackage.CONTACT_WAIT_STATEMENT__EVENT, oldEvent, event));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ContactPosition getContact()
  {
    return contact;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContact(ContactPosition newContact)
  {
    ContactPosition oldContact = contact;
    contact = newContact == null ? CONTACT_EDEFAULT : newContact;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailSLPackage.CONTACT_WAIT_STATEMENT__CONTACT, oldContact, contact));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RailSegment getSegment()
  {
    return segment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSegment(RailSegment newSegment)
  {
    RailSegment oldSegment = segment;
    segment = newSegment == null ? SEGMENT_EDEFAULT : newSegment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailSLPackage.CONTACT_WAIT_STATEMENT__SEGMENT, oldSegment, segment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RailSLPackage.CONTACT_WAIT_STATEMENT__EVENT:
        return getEvent();
      case RailSLPackage.CONTACT_WAIT_STATEMENT__CONTACT:
        return getContact();
      case RailSLPackage.CONTACT_WAIT_STATEMENT__SEGMENT:
        return getSegment();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RailSLPackage.CONTACT_WAIT_STATEMENT__EVENT:
        setEvent((ContactEvent)newValue);
        return;
      case RailSLPackage.CONTACT_WAIT_STATEMENT__CONTACT:
        setContact((ContactPosition)newValue);
        return;
      case RailSLPackage.CONTACT_WAIT_STATEMENT__SEGMENT:
        setSegment((RailSegment)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RailSLPackage.CONTACT_WAIT_STATEMENT__EVENT:
        setEvent(EVENT_EDEFAULT);
        return;
      case RailSLPackage.CONTACT_WAIT_STATEMENT__CONTACT:
        setContact(CONTACT_EDEFAULT);
        return;
      case RailSLPackage.CONTACT_WAIT_STATEMENT__SEGMENT:
        setSegment(SEGMENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RailSLPackage.CONTACT_WAIT_STATEMENT__EVENT:
        return event != EVENT_EDEFAULT;
      case RailSLPackage.CONTACT_WAIT_STATEMENT__CONTACT:
        return contact != CONTACT_EDEFAULT;
      case RailSLPackage.CONTACT_WAIT_STATEMENT__SEGMENT:
        return segment != SEGMENT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (event: ");
    result.append(event);
    result.append(", contact: ");
    result.append(contact);
    result.append(", segment: ");
    result.append(segment);
    result.append(')');
    return result.toString();
  }

} //ContactWaitStatementImpl
