/*
 * generated by Xtext 2.37.0
 */
package de.cau.cs.kieler.railsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRailSLScopeProvider extends DelegatingScopeProvider {
}
